#! /bin/sh

### BEGIN INIT INFO
# Provides:		brightness
# Required-Start:	$local_fs $remote_fs x11-common
# Required-Stop:	$local_fs $remote_fs
# Default-Start:	2 3 4 5
# Default-Stop:		
# Short-Description:	Set brighness
### END INIT INFO

set -e

export PATH="${PATH:+$PATH:}/usr/sbin:/sbin"

case "$1" in
  start)
	if start-stop-daemon --start --quiet --oknodo --pidfile /var/run/brightness.pid --exec /usr/bin/brightness -- ; then
	    log_end_msg 0 || true
	else
	    log_end_msg 1 || true
	fi
	;;
  stop)
	log_daemon_msg "Stopping brightness" "brightness" || true
	if start-stop-daemon --stop --quiet --oknodo --pidfile /var/run/brightness.pid; then
	    log_end_msg 0 || true
	else
	    log_end_msg 1 || true
	fi
	;;

  reload|force-reload)
	log_daemon_msg "Reloading brightness" "brightness" || true
	if start-stop-daemon --stop --signal 1 --quiet --oknodo --pidfile /var/run/brightness.pid --exec /usr/bin/brightness; then
	    log_end_msg 0 || true
	else
	    log_end_msg 1 || true
	fi
	;;

  restart)
	log_daemon_msg "Restarting brightness" "brightness" || true
	start-stop-daemon --stop --quiet --oknodo --retry 30 --pidfile /var/run/brightness.pid
	if start-stop-daemon --start --quiet --oknodo --pidfile /var/run/brightness.pid --exec /usr/bin/brightness --; then
	    log_end_msg 0 || true
	else
	    log_end_msg 1 || true
	fi
	;;

  status)
	status_of_proc -p /var/run/brightness.pid /usr/bin/brightness brightness && exit 0 || exit $?
	;;

  *)
	log_action_msg "Usage: /etc/init.d/brightness {start|stop|reload|force-reload|restart|status}" || true
	exit 1
esac

exit 0
